vac: 
	g++ -g -std=gnu++11 ./main.cpp ./neu.cpp ./objects.cpp -lm -fopenmp -D ADV -D KO -D VACUUM -o main 
int: 
	g++ -g -O3 -std=gnu++11 ./main.cpp ./neu.cpp ./objects.cpp -fopenmp -lm -D INT_VV  -D ADV -D KO -o main
adv:
	g++ -g -std=gnu++11 ./main.cpp ./neu.cpp ./objects.cpp -lm -fopenmp -D KO -D ADV -o main

