vac: 
	g++ -g -std=gnu++11 ./main.cpp ./neu.cpp -lm -fopenmp -D ADV -D KO -D VACUUM -o main 
int: 
	g++ -g -std=gnu++11 ./main.cpp ./neu.cpp -lm -fopenmp -D INT_VV -D KO -D ADV -o main
adv:
	g++ -g -std=gnu++11 ./main.cpp ./neu.cpp -lm -fopenmp -D KO -D ADV -o main

